services:
  db:
    image: postgres:16.3
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    env_file:
      - .env 
    volumes:
      - db:/var/lib/postgresql
  
  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  db: